//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nokia3310.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Levels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Levels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nokia3310.Resources.Levels", typeof(Levels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnakeLevels {
            get {
                return ResourceManager.GetString("SnakeLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///                &quot;                            &quot;,
        ///                &quot; ÛÛÛÛ Û   Û  ÛÛÛ  Û  Û ÛÛÛÛ &quot;,
        ///                &quot; Û    ÛÛ  Û Û   Û Û Û  Û    &quot;,
        ///                &quot; ÛÛÛÛ Û Û Û ÛÛÛÛÛ ÛÛ   ÛÛÛÛ &quot;,
        ///                &quot;    Û Û  ÛÛ Û   Û Û Û  Û    &quot;,
        ///                &quot; ÛÛÛÛ Û   Û Û   Û Û  Û ÛÛÛÛ &quot;,
        ///                &quot;                            &quot;,
        ///                &quot;                            &quot;,
        ///                &quot;   ÛÛÛÛÛÛÛÛÛÛÛ     ÛÛÛÛÛ  * &quot;,
        ///                &quot;   Û         Û     Û        &quot;,
        ///                &quot;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SnakeTitle {
            get {
                return ResourceManager.GetString("SnakeTitle", resourceCulture);
            }
        }
    }
}
